### ISSUE TITLE
Can't Install

### ISSUE THREAD

**Issue by SoilentBrad** [OmegaRogue/pf2e-mobile-sheet#12]
Received error when attempting to install in Foundry: 

Error: Unable to load valid module manifest data from "https://github.com/OmegaRogue/pf2e-mobile-sheet/releases/latest/download/module.json" No module manifest found at https://github.com/OmegaRogue/pf2e-mobile-sheet/releases/latest/download/module.json

Hopefully you can get this fixed soon. I have a player for our first time playing PF2 tomorrow who only has a tablet.

**Comment by OmegaRogue** [comment]
It should work now, but this module is currently only focused on phone compatibility, the larger screen of a tablet makes most if not all of this module unnecessary

**Comment by SoilentBrad** [comment]
Oh, that’s good to know. At least I helped you get it fixed for the people who need it 🙂

**Comment by OmegaRogue** [comment]
Seems like i shouldnt mark releases as prerelease anymore... thats what caused the issue
