### ISSUE TITLE
Proficiencie containers: wrong text in desktop mode because of i18n

### ISSUE THREAD

**Issue by HietsoM** [OmegaRogue/pf2e-mobile-sheet#13]
The proficiences boxes are to small in desktop mode:
![grafik](https://github.com/OmegaRogue/pf2e-mobile-sheet/assets/38157812/2c81cdee-02f7-46ea-97c0-73e84cec8fc3)
When you disable the module its looks normal:
![grafik](https://github.com/OmegaRogue/pf2e-mobile-sheet/assets/38157812/48a73fdf-3118-4969-8b4b-86634c0e3301)

This changes should only effect the mobile mode and not the desktop mode.

**Comment by Dorako** [comment]
Also affects the proficiencies in the red banner sidebar on PC sheets, and shortens "modifiers" to "mods"

**Comment by HietsoM** [comment]
With Module:
![grafik](https://github.com/OmegaRogue/pf2e-mobile-sheet/assets/38157812/cc0ee0ee-0b4d-4d0e-9d0f-d6b5e5db6284)
Withoud Module:
![grafik](https://github.com/OmegaRogue/pf2e-mobile-sheet/assets/38157812/007d62bc-26ae-47f2-b7f0-f5c0ab9aa8ae)

**Comment by OmegaRogue** [comment]
yes, this was something introduced by doing internationalization to override the text instead of replacing it
