### ISSUE TITLE
Make damage formula easiler to see

### ISSUE THREAD

**Issue by AlphaStarguide** [OmegaRogue/pf2e-mobile-sheet#14]
Now if you want to view the damage formula, you need to long-press the 'DAMAGE' button.
This might accidentally drag the item you didn't mean to. 
Perhaps there are easier ways to view the formula.
See the picuture ~~which I stolen from discord~~
![image](https://github.com/OmegaRogue/pf2e-mobile-sheet/assets/90250769/8b3487b9-f53e-4aad-9e02-184f3949f428)

**Comment by OmegaRogue** [comment]
Are you thinking of any ways to do this?

**Comment by AlphaStarguide** [comment]
Unfortunately I know nothing about coding so I'm afrid that I can't provide any technical advice.
Form a user's perspective, it would be nice if you could let damage formula displays like Strike dose,
such like [DAMAGE 1d6+4 piercing].

**Comment by OmegaRogue** [comment]
> Unfortunately I know nothing about coding so I'm afrid that I can't provide any technical advice.
> Form a user's perspective, it would be nice if you could let damage formula displays like Strike dose,
> such like [DAMAGE 1d6+4 piercing].

I was asking from a purely user perspective
Problem with thqt approach is that it takes up alot of space, which there isnt much available of

**Comment by AlphaStarguide** [comment]
> > Unfortunately I know nothing about coding so I'm afrid that I can't provide any technical advice.
> > Form a user's perspective, it would be nice if you could let damage formula displays like Strike dose,
> > such like [DAMAGE 1d6+4 piercing].
> 
> I was asking from a purely user perspective Problem with thqt approach is that it takes up alot of space, which there isnt much available of

Maybe... add a new row and move DAMAGE and CRITICAL to it? (between SHEATHE and STRIKE)

**Comment by dvanbale** [comment]
Hiya, I had the same problem and I solved it for my group:

![image](https://github.com/OmegaRogue/pf2e-mobile-sheet/assets/600409/e434e303-6050-4aee-af3e-9959db47b5ee)

I used the following CSS addition: 

```
button.tag.damage:after {
    content: '(' attr(data-tooltip) ')';
}
```
Hope this helps with a future fix/toggle?

**Comment by OmegaRogue** [comment]
> Hiya, I had the same problem and I solved it for my group:
> 
> ![image](https://private-user-images.githubusercontent.com/600409/282235267-e434e303-6050-4aee-af3e-9959db47b5ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5MjI3MTMsIm5iZiI6MTcwMDkyMjQxMywicGF0aCI6Ii82MDA0MDkvMjgyMjM1MjY3LWU0MzRlMzAzLTYwNTAtNGFlZS1hZjNlLTk5NTlkYjQ3YjVlZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyNVQxNDI2NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZDIzZmQwMzhlNDZlMjIyNDA3MzlhNjM5OTQ3MGQ0ZmM0MDZkYTJmYzRiZTI2ZGJmMTM3MjdlYjE4OGNkODRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SIpVr6XPfp04BsD68oE1bwPfrXKtCF8dnvDA5SLaXBY)
> 
> I used the following CSS addition:
> 
> ```
> button.tag.damage:after {
>     content: '(' attr(data-tooltip) ')';
> }
> ```
> 
> Hope this helps with a future fix/toggle?

I like the pure CSS solution, I'll probably use that, currently #16 is my top priority, tho that might be fixed in the next pf2e system version
