### ISSUE TITLE
Bug: The mobile design is no longer triggered in version 0.2.2

### ISSUE THREAD

**Issue by Rowiz49** [OmegaRogue/pf2e-mobile-sheet#15]
After updating to version 0.2.2, foundry on my phone doesn't change it's design, and character sheets also don't change responsively.
The setting to force mobile design is also gone.

**Comment by OmegaRogue** [comment]
Yes, I am investigating this issue, it seems like i am missing some part of the new setup, but I'm not sure yet what it is

**Comment by Rowiz49** [comment]
Thank you for all the good work, this module is super useful!
