### ISSUE TITLE
[Bug] Can't roll from sheet

### ISSUE THREAD

**Issue by Rowiz49** [OmegaRogue/pf2e-mobile-sheet#16]
When on mobile, pressing buttons like skills, strikes or saves doesn't trigger the roll dialog.

**Comment by OmegaRogue** [comment]
> When on mobile, pressing buttons like skills, strikes or saves doesn't trigger the roll dialog.

That seems to work for me, what versions are you on?

**Comment by Rowiz49** [comment]
- Foundry v11 build 315
- pathfinder 2e system v5.8.2
- pf2e mobile sheet v0.2.4

The rolling seems to be only disabled when in mobile.

**Comment by OmegaRogue** [comment]
> * Foundry v11 build 315
> 
>     * pathfinder 2e system v5.8.2
> 
>     * pf2e mobile sheet v0.2.4
> 
> 
> The rolling seems to be only disabled when in mobile.

do you have canvas disabled on mobile?

**Comment by Rowiz49** [comment]
Yes, I have it disabled

**Comment by OmegaRogue** [comment]
> Yes, I have it disabled

Ah, that explains it, they currently require a token selected which isnt possible, I'm working on a fix

**Comment by Rowiz49** [comment]
Understood, thanks for the good work!

**Comment by OmegaRogue** [comment]
this seems to be a bug in the system, im working on fixing it

**Comment by OmegaRogue** [comment]
https://github.com/foundryvtt/pf2e/pull/11672

**Comment by Rowiz49** [comment]
It seems that now rolling can work, but right now it only triggers on the damage buttons.

**Comment by OmegaRogue** [comment]
> It seems that now rolling can work, but right now it only triggers on the damage buttons.

Disabling the canvas won't be supported in this module soon-ish, instead there will be an option to remove the canvas html element do disable it, too much of the system relies on the canvas for it to properly work without a canvas, and proxying everything using sockets is starting to be a pain

**Comment by OmegaRogue** [comment]
Merged into the system as of 5.12.4

**Comment by OmegaRogue** [comment]
Closed the wrong issue accidentally
