### ISSUE TITLE
Not possible to open item description 

### ISSUE THREAD

**Issue by dvanbale** [OmegaRogue/pf2e-mobile-sheet#17]
In the inventory screen it's not possible to click on the item on mobile devices to view the description.

![image](https://github.com/OmegaRogue/pf2e-mobile-sheet/assets/600409/111d6454-dd28-4fe8-b103-e7ad32553e90)

Expected behavior: 
![image](https://github.com/OmegaRogue/pf2e-mobile-sheet/assets/600409/c2bb1bb8-914a-4931-9932-2af555db1a1a)
Screen shows the details of the item.

Current behavior:
System initiates drag and sort functionality which prevents opening of the item detail.

**Comment by dvanbale** [comment]
I've fixed this for my personal games the following way:

I sacrificed the ability to drag sort the items and allowed the click to open the item detail.
```
   //disable drag and drop
        $('.inventory-items.item-list .list-row').bind('pointerdown', function(event){
            event.stopPropagation();
        });
```

This kills the dragsort functionality but allows the detail toggle to work as normally. Pointer events were being trouble some.

**Comment by OmegaRogue** [comment]
> I've fixed this for my personal games the following way:
> 
> I sacrificed the ability to drag sort the items and allowed the click to open the item detail.
> 
> ```
>    //disable drag and drop
>         $('.inventory-items.item-list .list-row').bind('pointerdown', function(event){
>             event.stopPropagation();
>         });
> ```
> 
> This kills the dragsort functionality but allows the detail toggle to work as normally. Pointer events were being trouble some.

yes, foundry v11 kinda killed touch stuff by improving support. I'm wondering on what a better solution for this might be

**Comment by dvanbale** [comment]
I had no luck trying to keep the drag and drop feature alive while allowing to open items. the touch events are way to broadly applied. If I figure something out I'll let you know.

**Comment by OmegaRogue** [comment]
> I had no luck trying to keep the drag and drop feature alive while allowing to open items. the touch events are way to broadly applied. If I figure something out I'll let you know.

there is a fix that works for touchvtt that might also fix this:
https://github.com/Oromis/touch-vtt/issues/61#issuecomment-1723727061

**Comment by OmegaRogue** [comment]
seems like this actually isnt related to that, ill have a look at it

**Comment by OmegaRogue** [comment]
> In the inventory screen it's not possible to click on the item on mobile devices to view the description.
> 
> ![image](https://private-user-images.githubusercontent.com/600409/282254155-111d6454-dd28-4fe8-b103-e7ad32553e90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0NDA4MjYsIm5iZiI6MTcwMTQ0MDUyNiwicGF0aCI6Ii82MDA0MDkvMjgyMjU0MTU1LTExMWQ2NDU0LWRkMjgtNGZlOC1iMTAzLWU3YWQzMjU1M2U5MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwMVQxNDIyMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMzE0ZmNmMTkzODhkYmMzODU5Zjg1ZjJhOGNmZjcwNmNiNjUyZmE2N2I5ODMyNjVmNGRjM2U2YmE5N2QyYWJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.z3sZZgdVTU8TpZ4yvoSK9BbLnBCjPcrV87p1kkohEWo)
> 
> Expected behavior: ![image](https://private-user-images.githubusercontent.com/600409/282254173-c2bb1bb8-914a-4931-9932-2af555db1a1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0NDA4MjYsIm5iZiI6MTcwMTQ0MDUyNiwicGF0aCI6Ii82MDA0MDkvMjgyMjU0MTczLWMyYmIxYmI4LTkxNGEtNDkzMS05OTMyLTJhZjU1NWRiMWExYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwMVQxNDIyMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOGI3Njk2MWE5ZTM3NjQ2MjQzZWVlNzhjYTA1YmY1NGU4ZDg5YTFhZWExNTIwZDgyYTE5MmJjZmE5OTgzMjJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.L74vcE3pZsWfNZLZVOyMEW5yTP_-3Chva4ZAiW0ofQ0) Screen shows the details of the item.
> 
> Current behavior: System initiates drag and sort functionality which prevents opening of the item detail.

is this actually still the case? i just tried it and cant get drag sort to work without the fix

**Comment by OmegaRogue** [comment]
Seems like this can be fixed  pretty easily in the system, by adding

```
delay: 500,
delayOnTouchOnly: true,
```
to `SORTABLE_BASE_OPTIONS` in `src/util/misc.ts` or `pf2e.mjs`, that adds a 500ms delay until drag sort is triggered. I submitted a pr to the system for that: https://github.com/foundryvtt/pf2e/pull/12900

**Comment by OmegaRogue** [comment]
PR merged, will be working in the next pf2e system version
