### ISSUE TITLE
[Bug] The button to show the sidebar has disappeared 

### ISSUE THREAD

**Issue by Rowiz49** [OmegaRogue/pf2e-mobile-sheet#18]
The button to show the red sidebar with the HP/AC/Saves info does not appear anymore with version 0.2.4, foundry 11 build 315 and pathfinder 2e v5.10.3.

![Screenshot_20231203-142540~2.png](https://github.com/OmegaRogue/pf2e-mobile-sheet/assets/93596067/67e7b6e3-190a-46a9-8a2b-337780352790)

**Comment by dvanbale** [comment]
Developer note:

This PR changed the title from navigation-title to panel title.

https://github.com/foundryvtt/pf2e/pull/11798/commits/225f17c6b60d40ba6723ea6638fc8e966df7b9a1
