### ISSUE TITLE
Mobile Sheet Affects Other Windows

### ISSUE THREAD

**Issue by SoilentBrad** [OmegaRogue/pf2e-mobile-sheet#26]
Hi, there. I noticed in my game last night that things like the Wall window were strangely skinny while using the Foundry program (I was not going through a different browser, nor on mobile). 

![image](https://github.com/OmegaRogue/pf2e-mobile-sheet/assets/34387235/8d57d9ad-9a9a-4b1e-a63f-0f25e6368436)

I used Find the Culprit, and confirmed that it was PF2e Mobile Sheet that was causing the error.

**Comment by OmegaRogue** [comment]
Ah, so its not just me having that, ill look into it more then

**Comment by OmegaRogue** [comment]
I have absolutely no idea whats going on here

**Comment by OmegaRogue** [comment]
i now have an idea, seems like the module is working too well and its defaulting to some kind of default minimum width which is quite a bit smaller than it normally is because of the tweaks this module does
