### ISSUE TITLE
Request: Mobile Token Controls

### ISSUE THREAD

**Issue by micjevans** [OmegaRogue/pf2e-mobile-sheet#35]
Really great module first off!!! A small frustration with the project however is that there is no way to move a character on the scene from a phone. Two thoughts here. One is that you could absorb some of the TouchVTT modules functionality. It used to allow dragging tokens around with touch screens as well as using pinching to zoom in or zoom out. These would make for a pretty amazing foundry mobile experience with this gorgeous mobile sheet

Another possibility would be adding a joystick to the canvas page. Beavers-gamepad has one that doesn't function well here because it will render over the mobile sheet but it would probably be pretty easy to implement 4 arrow buttons to render on or instead of the canvas. This would make for a great "hotseat" experience where players have their sheet and controls on their phone while a DM renders the visuals on a shared screen.

Happy to help if you need any. Great work on what you've done already.

**Comment by tuhs1985** [comment]
Don't know if this helps, but I found that https://foundryvtt.com/packages/touch-vtt seems to be compatible with this module (or at least they don't break each other).  Gave me access to ruler and movement while canvas was enabled

**Comment by OmegaRogue** [comment]
> Don't know if this helps, but I found that https://foundryvtt.com/packages/touch-vtt seems to be compatible with this module (or at least they don't break each other). Gave me access to ruler and movement while canvas was enabled

usage together with touchvtt is intended, tho there will be more for this in this module soon :tm:
