### ISSUE TITLE
V10 compatibility warnings

### ISSUE THREAD

**Issue by xyzzy42** [OmegaRogue/pf2e-mobile-sheet#38]
There are a ton of V10 compat warnings when using the module.  The source appears to be `get icon()` in windowManager.ts, which is using the old `data` path.

https://github.com/OmegaRogue/pf2e-mobile-sheet/blob/673bba9e14923abbee09d9b5ed61979369c15deb/src/module/apps/windowManager.ts#L65-L67

The former could be `this.app?.object?.type`, but IDK where entity comes from.

**Comment by OmegaRogue** [comment]
fixed in 0.7.0
