### ISSUE TITLE
Compatibility error with Foundry 12.327

### ISSUE THREAD

**Issue by markhop1** [OmegaRogue/pf2e-mobile-sheet#40]
I've encountered this issue after upgrading my world to `Foundry 12.327 `and `Pathfinder 6.0.2`

![image](https://github.com/OmegaRogue/pf2e-mobile-sheet/assets/11248375/60e79f50-f0c6-4546-a1a2-3235f9d3dbad)
![image](https://github.com/OmegaRogue/pf2e-mobile-sheet/assets/11248375/b52cfd4c-1a9e-4b52-89b9-50ed82ae89df)

**Comment by OmegaRogue** [comment]
Does anything break? that looks like old touch compatibility stuff not working anymore, because afaik touch got fixed in core

**Comment by markhop1** [comment]
I didn't notice anything broken yet, just saw that warning

**Comment by arthurcannon** [comment]
The window switcher does not bring up the menu of windows.
![Screenshot from 2024-07-26 15-28-20](https://github.com/user-attachments/assets/22212b83-4d39-4375-a5e6-88b5d8a118fa)
![Screenshot from 2024-07-26 15-33-12](https://github.com/user-attachments/assets/3c83591c-15c1-4d8b-89f5-40aed470c62f)

**Comment by OmegaRogue** [comment]
I'm returning to development once again, so expect to see this dealt with soon :tm:

**Comment by OmegaRogue** [comment]
fixed in 0.7.0
